DROP SEQUENCE SQL_PROCUREMENT_NOTIFICATIONM_ID;

DROP SEQUENCE SQL_PROCUREMENT_TO_DO_LIST_ITEM_ID;

DROP SEQUENCE SQL_PROCUREMENT_ORDER_ITEM_ID;

DROP SEQUENCE SQL_PROCUREMENT_ORDER_ID;

DROP SEQUENCE SQL_PROCUREMENT_SKU_ID;

DROP SEQUENCE SQL_PROCUREMENT_OFFICE_DEPOT_ID;

DROP SEQUENCE SQL_PROCUREMENT_PRICE_ID;

DROP SEQUENCE SQL_PROCUREMENT_CATALOG_ID;

DROP SEQUENCE SQL_PROCUREMENT_USER_INFO_ID;

DROP SEQUENCE SQL_PROCUREMENT_USER_ID;

DROP TABLE NOTIFICATION;

DROP TABLE TO_DO_LIST_ITEM;

DROP TABLE ACTION_MAPPING;

DROP TABLE ACTION_TYPE;

DROP TABLE TO_DO_LIST_TYPE;

DROP TABLE MANAGEMENT_TYPE;

DROP TABLE INITIAL_STATE_TYPE;

DROP TABLE ORDER_ITEM;

DROP TABLE ORDERS;

DROP TABLE ORDER_TYPE;

DROP TABLE ORDER_STATUS;

DROP TABLE SKU;

DROP TABLE OFFICE_DEPOT;

DROP TABLE SKU_TYPE;

DROP TABLE PRICE;

DROP TABLE CURRENCY_TYPE;

DROP TABLE CATALOG;

DROP TABLE USER_INFO;

DROP TABLE USER_INFO_TYPE;

DROP TABLE USERS;

DROP TABLE USER_STATUS;

DROP TABLE USER_ROLE;